### PR TITLE
Use Device Tree for RPi screen

### PR DESCRIPTION
**Pull request by Tonymac32**
Rolls back changes to rockchip.c for the 7" RPi touchscreen, instead putting it in the device tree for Tinker Board.

Removes unused asus_mcu driver files.

Be sure to test/verify before merge, this may be better as an overlay, for instance.

### CODE REVIEW

**Comment by jamess-huang** [comment]
Thanks for the pull request, we will test the patch.

**Comment by jamess-huang** [comment]
Hi, 
     We have applied this patch at our internal server and will be released to github when we announce the next image release to end user. If you have no concern, I will close this PR request.

**Comment by Tonymac32** [comment]
Sounds good, thank you.

**Comment by PeterDaveHello** [comment]
@jamess-huang will it be possible to directly merge the pull request on GitHub? Thanks!

**Comment by TinkerTeam** [comment]
Dear @Tonymac32 

We create two new branches for Kernel & U-Boot:
- [develop](https://github.com/TinkerBoard/debian_kernel/tree/develop): 
Now start to push & sync our internally have been validated's commits to this branch.
- [release](https://github.com/TinkerBoard/debian_kernel/tree/release): 
Keep sync commit based on our released image as usual.

So you can find your codes on this commit on `develop` branch https://github.com/TinkerBoard/debian_kernel/commit/4575d6f7620755235fe821646fb6c4d341025ca6.
And when we have a release version, also can found it on `release` branch.
Thanks.

**Pull request closed without merging**
